require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegionStatisticsController do

  # This should return the minimal set of attributes required to create a valid
  # RegionStatistic. As you add validations to RegionStatistic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "usage" => "1.5" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegionStatisticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all region_statistics as @region_statistics" do
      region_statistic = RegionStatistic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:region_statistics).should eq([region_statistic])
    end
  end

  describe "GET show" do
    it "assigns the requested region_statistic as @region_statistic" do
      region_statistic = RegionStatistic.create! valid_attributes
      get :show, {:id => region_statistic.to_param}, valid_session
      assigns(:region_statistic).should eq(region_statistic)
    end
  end

  describe "GET new" do
    it "assigns a new region_statistic as @region_statistic" do
      get :new, {}, valid_session
      assigns(:region_statistic).should be_a_new(RegionStatistic)
    end
  end

  describe "GET edit" do
    it "assigns the requested region_statistic as @region_statistic" do
      region_statistic = RegionStatistic.create! valid_attributes
      get :edit, {:id => region_statistic.to_param}, valid_session
      assigns(:region_statistic).should eq(region_statistic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RegionStatistic" do
        expect {
          post :create, {:region_statistic => valid_attributes}, valid_session
        }.to change(RegionStatistic, :count).by(1)
      end

      it "assigns a newly created region_statistic as @region_statistic" do
        post :create, {:region_statistic => valid_attributes}, valid_session
        assigns(:region_statistic).should be_a(RegionStatistic)
        assigns(:region_statistic).should be_persisted
      end

      it "redirects to the created region_statistic" do
        post :create, {:region_statistic => valid_attributes}, valid_session
        response.should redirect_to(RegionStatistic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved region_statistic as @region_statistic" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:region_statistic => { "usage" => "invalid value" }}, valid_session
        assigns(:region_statistic).should be_a_new(RegionStatistic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:region_statistic => { "usage" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested region_statistic" do
        region_statistic = RegionStatistic.create! valid_attributes
        # Assuming there are no other region_statistics in the database, this
        # specifies that the RegionStatistic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RegionStatistic.any_instance.should_receive(:update).with({ "usage" => "1.5" })
        put :update, {:id => region_statistic.to_param, :region_statistic => { "usage" => "1.5" }}, valid_session
      end

      it "assigns the requested region_statistic as @region_statistic" do
        region_statistic = RegionStatistic.create! valid_attributes
        put :update, {:id => region_statistic.to_param, :region_statistic => valid_attributes}, valid_session
        assigns(:region_statistic).should eq(region_statistic)
      end

      it "redirects to the region_statistic" do
        region_statistic = RegionStatistic.create! valid_attributes
        put :update, {:id => region_statistic.to_param, :region_statistic => valid_attributes}, valid_session
        response.should redirect_to(region_statistic)
      end
    end

    describe "with invalid params" do
      it "assigns the region_statistic as @region_statistic" do
        region_statistic = RegionStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_statistic.to_param, :region_statistic => { "usage" => "invalid value" }}, valid_session
        assigns(:region_statistic).should eq(region_statistic)
      end

      it "re-renders the 'edit' template" do
        region_statistic = RegionStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_statistic.to_param, :region_statistic => { "usage" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested region_statistic" do
      region_statistic = RegionStatistic.create! valid_attributes
      expect {
        delete :destroy, {:id => region_statistic.to_param}, valid_session
      }.to change(RegionStatistic, :count).by(-1)
    end

    it "redirects to the region_statistics list" do
      region_statistic = RegionStatistic.create! valid_attributes
      delete :destroy, {:id => region_statistic.to_param}, valid_session
      response.should redirect_to(region_statistics_url)
    end
  end

end
