require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsageTypesController do

  # This should return the minimal set of attributes required to create a valid
  # UsageType. As you add validations to UsageType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "indirection" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsageTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all usage_types as @usage_types" do
      usage_type = UsageType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:usage_types).should eq([usage_type])
    end
  end

  describe "GET show" do
    it "assigns the requested usage_type as @usage_type" do
      usage_type = UsageType.create! valid_attributes
      get :show, {:id => usage_type.to_param}, valid_session
      assigns(:usage_type).should eq(usage_type)
    end
  end

  describe "GET new" do
    it "assigns a new usage_type as @usage_type" do
      get :new, {}, valid_session
      assigns(:usage_type).should be_a_new(UsageType)
    end
  end

  describe "GET edit" do
    it "assigns the requested usage_type as @usage_type" do
      usage_type = UsageType.create! valid_attributes
      get :edit, {:id => usage_type.to_param}, valid_session
      assigns(:usage_type).should eq(usage_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UsageType" do
        expect {
          post :create, {:usage_type => valid_attributes}, valid_session
        }.to change(UsageType, :count).by(1)
      end

      it "assigns a newly created usage_type as @usage_type" do
        post :create, {:usage_type => valid_attributes}, valid_session
        assigns(:usage_type).should be_a(UsageType)
        assigns(:usage_type).should be_persisted
      end

      it "redirects to the created usage_type" do
        post :create, {:usage_type => valid_attributes}, valid_session
        response.should redirect_to(UsageType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved usage_type as @usage_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsageType.any_instance.stub(:save).and_return(false)
        post :create, {:usage_type => { "indirection" => "invalid value" }}, valid_session
        assigns(:usage_type).should be_a_new(UsageType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsageType.any_instance.stub(:save).and_return(false)
        post :create, {:usage_type => { "indirection" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested usage_type" do
        usage_type = UsageType.create! valid_attributes
        # Assuming there are no other usage_types in the database, this
        # specifies that the UsageType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UsageType.any_instance.should_receive(:update).with({ "indirection" => "1" })
        put :update, {:id => usage_type.to_param, :usage_type => { "indirection" => "1" }}, valid_session
      end

      it "assigns the requested usage_type as @usage_type" do
        usage_type = UsageType.create! valid_attributes
        put :update, {:id => usage_type.to_param, :usage_type => valid_attributes}, valid_session
        assigns(:usage_type).should eq(usage_type)
      end

      it "redirects to the usage_type" do
        usage_type = UsageType.create! valid_attributes
        put :update, {:id => usage_type.to_param, :usage_type => valid_attributes}, valid_session
        response.should redirect_to(usage_type)
      end
    end

    describe "with invalid params" do
      it "assigns the usage_type as @usage_type" do
        usage_type = UsageType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsageType.any_instance.stub(:save).and_return(false)
        put :update, {:id => usage_type.to_param, :usage_type => { "indirection" => "invalid value" }}, valid_session
        assigns(:usage_type).should eq(usage_type)
      end

      it "re-renders the 'edit' template" do
        usage_type = UsageType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsageType.any_instance.stub(:save).and_return(false)
        put :update, {:id => usage_type.to_param, :usage_type => { "indirection" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested usage_type" do
      usage_type = UsageType.create! valid_attributes
      expect {
        delete :destroy, {:id => usage_type.to_param}, valid_session
      }.to change(UsageType, :count).by(-1)
    end

    it "redirects to the usage_types list" do
      usage_type = UsageType.create! valid_attributes
      delete :destroy, {:id => usage_type.to_param}, valid_session
      response.should redirect_to(usage_types_url)
    end
  end

end
